In [1]:
import numpy as np
np.linspace(-3,3)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [2]:
array = np.linspace(-3,3,num=100)
array * 10

array([-30.        , -29.39393939, -28.78787879, -28.18181818,
       -27.57575758, -26.96969697, -26.36363636, -25.75757576,
       -25.15151515, -24.54545455, -23.93939394, -23.33333333,
       -22.72727273, -22.12121212, -21.51515152, -20.90909091,
       -20.3030303 , -19.6969697 , -19.09090909, -18.48484848,
       -17.87878788, -17.27272727, -16.66666667, -16.06060606,
       -15.45454545, -14.84848485, -14.24242424, -13.63636364,
       -13.03030303, -12.42424242, -11.81818182, -11.21212121,
       -10.60606061, -10.        ,  -9.39393939,  -8.78787879,
        -8.18181818,  -7.57575758,  -6.96969697,  -6.36363636,
        -5.75757576,  -5.15151515,  -4.54545455,  -3.93939394,
        -3.33333333,  -2.72727273,  -2.12121212,  -1.51515152,
        -0.90909091,  -0.3030303 ,   0.3030303 ,   0.90909091,
         1.51515152,   2.12121212,   2.72727273,   3.33333333,
         3.93939394,   4.54545455,   5.15151515,   5.75757576,
         6.36363636,   6.96969697,   7.57575758,   8.18

In [3]:
np.random.randint(50,size=100,high=101)

array([ 56,  62,  90,  70,  76,  68,  90,  88,  97,  84,  52,  75,  83,
        96,  99,  94,  52,  98,  62,  89,  71,  57,  90,  64,  83,  88,
        87,  92,  93,  67,  90,  54,  89,  61,  66,  95,  99,  73,  69,
        59,  70,  65,  60,  55,  78,  84,  72,  70,  90,  89,  82,  53,
        64, 100,  52,  72,  60,  92,  75,  62,  67,  96,  60,  98,  55,
        81,  58,  70,  80,  68,  97,  72,  71,  55,  71,  68,  75,  68,
        88,  88,  84,  96,  74, 100,  61,  75,  87,  99,  77,  83,  82,
        68,  88,  91,  80,  64,  83,  66,  90,  58])

In [4]:
content = np.random.randint(50,size=(50,5),high=101)

In [5]:
import pandas as pd
df1 = pd.DataFrame(data=content,
             index=[f"第{i}號"for i in range(1,51)],
             columns=['國文','英文','數學','地理','歷史'])
df1

國文   英文   數學  地理  歷史
第1號    74   89   91  64  81
第2號    69   86  100  77  98
第3號    55   74   96  77  91
第4號    95   67   90  64  92
第5號   100   97  100  92  93
第6號    81   63   75  77  94
第7號    69   77   55  99  96
第8號    73   83   54  60  55
第9號    77   78   80  94  74
第10號   59   75   94  53  77
第11號   66   86   66  57  90
第12號   68   83   81  74  54
第13號   68   80   94  56  72
第14號   87   75   83  65  93
第15號   69   84   76  93  54
第16號   83   92   86  90  67
第17號   79   54   60  70  85
第18號   84   93   64  65  51
第19號   81   51   70  59  50
第20號   78   85   62  83  72
第21號   96   91   61  77  90
第22號   57   99   83  98  93
第23號  100   84   78  85  99
第24號   79   74   74  84  52
第25號   86   71   74  56  57
第26號   54   52   67  60  73
第27號   79   92   98  51  99
第28號   56   57   92  91  98
第29號   82  100   81  67  74
第30號   79   95   54  68  99
第31號   57   70   58  75  97
第32號   80   76   58  97  79
第33號   52   79   75  61  64
第34號   96   95   52  52  55
第35號   77   59   77  66  58
第36號   85   93   52  74  82
第37號   69   62   74  63  85
第38號   53   99   78  99  66
第39號   83   65   93  74  98
第40號   90   72   71  93  56
第41號   86   96   57  84  61
第42號   82   63   66  78  56
第43號   51   61   61  81  55
第44號   58   88   58  81  80
第45號   77   72   57  51  81
第46號   69   67   66  58  74
第47號  100   82   63  90  80
第48號   77   53   98  87  59
第49號   63   77   73  62  87
第50號   81   97   92  59  59

In [6]:
df1.loc["第1號",:]

國文    74
英文    89
數學    91
地理    64
歷史    81
Name: 第1號, dtype: int64

In [7]:
df1.loc["第1號"]

國文    74
英文    89
數學    91
地理    64
歷史    81
Name: 第1號, dtype: int64

In [8]:
df1.loc[["第1號","第5號","第10號"]]

國文  英文   數學  地理  歷史
第1號    74  89   91  64  81
第5號   100  97  100  92  93
第10號   59  75   94  53  77

In [9]:
df1.iloc[:5]

國文  英文   數學  地理  歷史
第1號   74  89   91  64  81
第2號   69  86  100  77  98
第3號   55  74   96  77  91
第4號   95  67   90  64  92
第5號  100  97  100  92  93

In [10]:
df1.iloc[-5:]

國文  英文  數學  地理  歷史
第46號   69  67  66  58  74
第47號  100  82  63  90  80
第48號   77  53  98  87  59
第49號   63  77  73  62  87
第50號   81  97  92  59  59

In [11]:
df1.loc['第10號':'第15號']

國文  英文  數學  地理  歷史
第10號  59  75  94  53  77
第11號  66  86  66  57  90
第12號  68  83  81  74  54
第13號  68  80  94  56  72
第14號  87  75  83  65  93
第15號  69  84  76  93  54

In [12]:
student_sum = df1.sum(axis=1)
student_mean = df1.mean(axis=1)
df1['總分'] = student_sum
df1['平均'] = student_mean


In [13]:
df2 = df1.sort_values(by='總分',ascending=False)

In [14]:
df2.iloc[:5]

國文  英文   數學  地理  歷史   總分    平均
第5號   100  97  100  92  93  482  96.4
第23號  100  84   78  85  99  446  89.2
第22號   57  99   83  98  93  430  86.0
第2號    69  86  100  77  98  430  86.0
第27號   79  92   98  51  99  419  83.8

In [15]:
df2.iloc[-5:]

國文  英文  數學  地理  歷史   總分    平均
第33號  52  79  75  61  64  331  66.2
第8號   73  83  54  60  55  325  65.0
第19號  81  51  70  59  50  311  62.2
第43號  51  61  61  81  55  309  61.8
第26號  54  52  67  60  73  306  61.2

In [23]:
df2['排名'] = df1['總分'].rank(method='first',ascending=False).astype(int)


In [24]:
df2

國文   英文   數學  地理  歷史   總分    平均  排名
第5號   100   97  100  92  93  482  96.4   1
第23號  100   84   78  85  99  446  89.2   2
第22號   57   99   83  98  93  430  86.0   4
第2號    69   86  100  77  98  430  86.0   3
第27號   79   92   98  51  99  419  83.8   5
第16號   83   92   86  90  67  418  83.6   6
第21號   96   91   61  77  90  415  83.0   7
第47號  100   82   63  90  80  415  83.0   8
第39號   83   65   93  74  98  413  82.6   9
第4號    95   67   90  64  92  408  81.6  10
第29號   82  100   81  67  74  404  80.8  11
第14號   87   75   83  65  93  403  80.6  13
第9號    77   78   80  94  74  403  80.6  12
第1號    74   89   91  64  81  399  79.8  14
第7號    69   77   55  99  96  396  79.2  15
第30號   79   95   54  68  99  395  79.0  16
第38號   53   99   78  99  66  395  79.0  17
第28號   56   57   92  91  98  394  78.8  18
第3號    55   74   96  77  91  393  78.6  19
第6號    81   63   75  77  94  390  78.0  20
第32號   80   76   58  97  79  390  78.0  21
第50號   81   97   92  59  59  388  77.6  22
第36號   85   93   52  74  82  386  77.2  23
第41號   86   96   57  84  61  384  76.8  24
第40號   90   72   71  93  56  382  76.4  25
第20號   78   85   62  83  72  380  76.0  26
第15號   69   84   76  93  54  376  75.2  27
第48號   77   53   98  87  59  374  74.8  28
第13號   68   80   94  56  72  370  74.0  29
第44號   58   88   58  81  80  365  73.0  31
第11號   66   86   66  57  90  365  73.0  30
第24號   79   74   74  84  52  363  72.6  32
第49號   63   77   73  62  87  362  72.4  33
第12號   68   83   81  74  54  360  72.0  34
第10號   59   75   94  53  77  358  71.6  35
第31號   57   70   58  75  97  357  71.4  37
第18號   84   93   64  65  51  357  71.4  36
第37號   69   62   74  63  85  353  70.6  38
第34號   96   95   52  52  55  350  70.0  39
第17號   79   54   60  70  85  348  69.6  40
第42號   82   63   66  78  56  345  69.0  41
第25號   86   71   74  56  57  344  68.8  42
第45號   77   72   57  51  81  338  67.6  43
第35號   77   59   77  66  58  337  67.4  44
第46號   69   67   66  58  74  334  66.8  45
第33號   52   79   75  61  64  331  66.2  46
第8號    73   83   54  60  55  325  65.0  47
第19號   81   51   70  59  50  311  62.2  48
第43號   51   61   61  81  55  309  61.8  49
第26號   54   52   67  60  73  306  61.2  50