In [1]:
import numpy as np
np.linspace(-3,3)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [2]:
array = np.linspace(-3,3,num=100)
array * 10

array([-30.        , -29.39393939, -28.78787879, -28.18181818,
       -27.57575758, -26.96969697, -26.36363636, -25.75757576,
       -25.15151515, -24.54545455, -23.93939394, -23.33333333,
       -22.72727273, -22.12121212, -21.51515152, -20.90909091,
       -20.3030303 , -19.6969697 , -19.09090909, -18.48484848,
       -17.87878788, -17.27272727, -16.66666667, -16.06060606,
       -15.45454545, -14.84848485, -14.24242424, -13.63636364,
       -13.03030303, -12.42424242, -11.81818182, -11.21212121,
       -10.60606061, -10.        ,  -9.39393939,  -8.78787879,
        -8.18181818,  -7.57575758,  -6.96969697,  -6.36363636,
        -5.75757576,  -5.15151515,  -4.54545455,  -3.93939394,
        -3.33333333,  -2.72727273,  -2.12121212,  -1.51515152,
        -0.90909091,  -0.3030303 ,   0.3030303 ,   0.90909091,
         1.51515152,   2.12121212,   2.72727273,   3.33333333,
         3.93939394,   4.54545455,   5.15151515,   5.75757576,
         6.36363636,   6.96969697,   7.57575758,   8.18

In [3]:
np.random.randint(50,size=100,high=101)

array([ 58,  50,  94,  77,  89,  82,  71,  99,  92,  63,  60,  75,  95,
        50,  69,  63,  72,  82,  54,  67,  69,  82,  73,  79,  92,  69,
        88,  95,  61,  90,  96,  80,  72,  87,  84,  85,  96,  65,  70,
        76,  70,  99,  57,  56,  92,  81,  86,  98,  69,  54,  63,  88,
        86,  89, 100,  60,  84,  52,  52,  79,  61,  76,  91,  81,  60,
        92,  50,  72,  83,  90,  78,  79,  86,  55,  72,  90,  78,  90,
        62,  51,  55,  72,  82,  71,  78,  70, 100,  83,  88,  97,  74,
        60,  89,  67,  55,  91,  53,  71,  96,  69])

In [4]:
content = np.random.randint(50,size=(50,5),high=101)

In [5]:
import pandas as pd
df1 = pd.DataFrame(data=content,
             index=[f"第{i}號"for i in range(1,51)],
             columns=['國文','英文','數學','地理','歷史'])
df1

國文   英文  數學   地理  歷史
第1號    54   79  69   93  53
第2號    50   81  61   55  70
第3號    67   58  89   89  93
第4號    70   78  87   94  88
第5號    59   97  95   83  73
第6號    78   51  87   72  89
第7號    66   95  52   99  88
第8號    92   61  65   82  87
第9號    59   97  84   93  80
第10號   51   57  61   92  52
第11號   87   68  96   93  53
第12號   83   53  90   61  74
第13號   68   57  94   61  81
第14號   61   90  54  100  72
第15號   92   65  84   91  51
第16號   83   95  52   88  78
第17號   75   53  65   69  77
第18號   78   62  53   70  84
第19號   91   85  75   79  81
第20號   98   88  85   50  61
第21號   75   95  78   80  64
第22號   75   85  61   88  79
第23號   64   81  58   53  55
第24號   98   98  93   81  92
第25號   71   62  52   90  99
第26號   98   54  84   96  94
第27號   61  100  50   73  56
第28號   94   80  88   66  95
第29號   61   52  74   83  89
第30號   61   61  93   53  84
第31號   98   96  91   67  78
第32號   78   87  93   95  85
第33號   67   55  67   58  78
第34號   94   53  50   67  51
第35號   64   50  59   65  67
第36號   95   81  71   89  54
第37號   97   90  82   64  97
第38號   66   53  57   76  62
第39號   57   70  70   62  65
第40號  100   64  98   84  54
第41號   70   56  89   90  84
第42號   80   60  71   54  75
第43號   93   73  90   94  78
第44號   59   83  83   74  70
第45號   78   61  84   57  67
第46號   84   93  57   99  99
第47號   57   73  73  100  97
第48號   93   95  59   76  83
第49號   70  100  60   71  54
第50號   64   50  71   83  91

In [6]:
df1.loc["第1號",:]

國文    54
英文    79
數學    69
地理    93
歷史    53
Name: 第1號, dtype: int64

In [7]:
df1.loc["第1號"]

國文    54
英文    79
數學    69
地理    93
歷史    53
Name: 第1號, dtype: int64

In [8]:
df1.loc[["第1號","第5號","第10號"]]

國文  英文  數學  地理  歷史
第1號   54  79  69  93  53
第5號   59  97  95  83  73
第10號  51  57  61  92  52

In [9]:
df1.iloc[:5]

國文  英文  數學  地理  歷史
第1號  54  79  69  93  53
第2號  50  81  61  55  70
第3號  67  58  89  89  93
第4號  70  78  87  94  88
第5號  59  97  95  83  73

In [10]:
df1.iloc[-5:]

國文   英文  數學   地理  歷史
第46號  84   93  57   99  99
第47號  57   73  73  100  97
第48號  93   95  59   76  83
第49號  70  100  60   71  54
第50號  64   50  71   83  91

In [11]:
df1.loc['第10號':'第15號']

國文  英文  數學   地理  歷史
第10號  51  57  61   92  52
第11號  87  68  96   93  53
第12號  83  53  90   61  74
第13號  68  57  94   61  81
第14號  61  90  54  100  72
第15號  92  65  84   91  51

In [12]:
student_sum = df1.sum(axis=1)
student_mean = df1.mean(axis=1)
df1['總分'] = student_sum
df1['平均'] = student_mean


In [13]:
df2 = df1.sort_values(by='總分',ascending=False)

In [14]:
df2.iloc[:5]

國文  英文  數學  地理  歷史   總分    平均
第24號  98  98  93  81  92  462  92.4
第32號  78  87  93  95  85  438  87.6
第46號  84  93  57  99  99  432  86.4
第31號  98  96  91  67  78  430  86.0
第37號  97  90  82  64  97  430  86.0

In [15]:
df2.iloc[-5:]

國文  英文  數學  地理  歷史   總分    平均
第34號  94  53  50  67  51  315  63.0
第38號  66  53  57  76  62  314  62.8
第10號  51  57  61  92  52  313  62.6
第23號  64  81  58  53  55  311  62.2
第35號  64  50  59  65  67  305  61.0

In [21]:
df2['排名'] = df1['總分'].rank(method='first',ascending=False)

In [22]:
df2

國文   英文  數學   地理  歷史   總分    平均    排名
第24號   98   98  93   81  92  462  92.4   1.0
第32號   78   87  93   95  85  438  87.6   2.0
第46號   84   93  57   99  99  432  86.4   3.0
第31號   98   96  91   67  78  430  86.0   4.0
第37號   97   90  82   64  97  430  86.0   5.0
第43號   93   73  90   94  78  428  85.6   6.0
第26號   98   54  84   96  94  426  85.2   7.0
第28號   94   80  88   66  95  423  84.6   8.0
第4號    70   78  87   94  88  417  83.4   9.0
第9號    59   97  84   93  80  413  82.6  10.0
第19號   91   85  75   79  81  411  82.2  11.0
第5號    59   97  95   83  73  407  81.4  12.0
第48號   93   95  59   76  83  406  81.2  13.0
第7號    66   95  52   99  88  400  80.0  14.0
第47號   57   73  73  100  97  400  80.0  16.0
第40號  100   64  98   84  54  400  80.0  15.0
第11號   87   68  96   93  53  397  79.4  17.0
第3號    67   58  89   89  93  396  79.2  18.0
第16號   83   95  52   88  78  396  79.2  19.0
第21號   75   95  78   80  64  392  78.4  20.0
第36號   95   81  71   89  54  390  78.0  21.0
第41號   70   56  89   90  84  389  77.8  22.0
第22號   75   85  61   88  79  388  77.6  23.0
第8號    92   61  65   82  87  387  77.4  24.0
第15號   92   65  84   91  51  383  76.6  25.0
第20號   98   88  85   50  61  382  76.4  26.0
第6號    78   51  87   72  89  377  75.4  27.0
第14號   61   90  54  100  72  377  75.4  28.0
第25號   71   62  52   90  99  374  74.8  29.0
第44號   59   83  83   74  70  369  73.8  30.0
第13號   68   57  94   61  81  361  72.2  32.0
第12號   83   53  90   61  74  361  72.2  31.0
第29號   61   52  74   83  89  359  71.8  33.0
第50號   64   50  71   83  91  359  71.8  34.0
第49號   70  100  60   71  54  355  71.0  35.0
第30號   61   61  93   53  84  352  70.4  36.0
第1號    54   79  69   93  53  348  69.6  37.0
第18號   78   62  53   70  84  347  69.4  38.0
第45號   78   61  84   57  67  347  69.4  39.0
第42號   80   60  71   54  75  340  68.0  41.0
第27號   61  100  50   73  56  340  68.0  40.0
第17號   75   53  65   69  77  339  67.8  42.0
第33號   67   55  67   58  78  325  65.0  43.0
第39號   57   70  70   62  65  324  64.8  44.0
第2號    50   81  61   55  70  317  63.4  45.0
第34號   94   53  50   67  51  315  63.0  46.0
第38號   66   53  57   76  62  314  62.8  47.0
第10號   51   57  61   92  52  313  62.6  48.0
第23號   64   81  58   53  55  311  62.2  49.0
第35號   64   50  59   65  67  305  61.0  50.0