In [1]:
import numpy as np
np.linspace(-3,3)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [2]:
array = np.linspace(-3,3,num=100)
array * 10

array([-30.        , -29.39393939, -28.78787879, -28.18181818,
       -27.57575758, -26.96969697, -26.36363636, -25.75757576,
       -25.15151515, -24.54545455, -23.93939394, -23.33333333,
       -22.72727273, -22.12121212, -21.51515152, -20.90909091,
       -20.3030303 , -19.6969697 , -19.09090909, -18.48484848,
       -17.87878788, -17.27272727, -16.66666667, -16.06060606,
       -15.45454545, -14.84848485, -14.24242424, -13.63636364,
       -13.03030303, -12.42424242, -11.81818182, -11.21212121,
       -10.60606061, -10.        ,  -9.39393939,  -8.78787879,
        -8.18181818,  -7.57575758,  -6.96969697,  -6.36363636,
        -5.75757576,  -5.15151515,  -4.54545455,  -3.93939394,
        -3.33333333,  -2.72727273,  -2.12121212,  -1.51515152,
        -0.90909091,  -0.3030303 ,   0.3030303 ,   0.90909091,
         1.51515152,   2.12121212,   2.72727273,   3.33333333,
         3.93939394,   4.54545455,   5.15151515,   5.75757576,
         6.36363636,   6.96969697,   7.57575758,   8.18

In [7]:
np.random.randint(50,size=100,high=101)

array([90, 62, 55, 97, 78, 94, 67, 93, 66, 91, 86, 65, 50, 51, 73, 72, 65,
       58, 75, 69, 95, 61, 78, 93, 51, 89, 66, 91, 73, 69, 83, 94, 58, 68,
       69, 69, 54, 90, 70, 94, 70, 64, 86, 54, 63, 85, 74, 82, 86, 53, 94,
       88, 78, 95, 86, 96, 51, 50, 78, 50, 81, 91, 99, 97, 69, 55, 84, 67,
       70, 58, 73, 93, 78, 77, 94, 93, 70, 94, 68, 94, 90, 81, 64, 99, 84,
       72, 97, 96, 71, 95, 60, 57, 65, 72, 63, 56, 53, 50, 71, 54])

In [8]:
np.random.randint(50,size=(50,5),high=101)

array([[ 80,  63,  74,  62,  61],
       [ 75,  60,  66,  63,  99],
       [ 66,  94,  86,  93,  77],
       [ 97,  57,  52,  84,  54],
       [ 71,  52,  92,  86,  98],
       [ 54,  50,  51,  67,  65],
       [ 55,  82,  83,  52,  61],
       [ 96,  50,  68,  56,  91],
       [ 55,  67, 100,  98,  72],
       [ 88,  67,  94,  55,  91],
       [ 98,  61,  70,  67,  53],
       [ 56,  61,  81,  60,  94],
       [ 64,  80,  98,  67,  58],
       [ 56,  58,  80,  91,  99],
       [ 57,  76,  94,  52,  61],
       [ 81,  76,  72,  70,  52],
       [ 66,  96,  75,  57, 100],
       [ 55,  56,  65,  90,  83],
       [ 76,  65,  73, 100,  80],
       [ 55,  50,  66,  57,  84],
       [ 56,  68,  63,  79,  67],
       [ 88,  89,  57,  96,  94],
       [ 86,  63,  92,  51,  67],
       [ 52,  67,  75,  59,  54],
       [ 97,  82,  72,  59,  78],
       [ 56,  65,  57,  67,  78],
       [ 53,  63, 100,  97,  61],
       [ 94,  92,  85,  76,  96],
       [ 81,  63,  97,  93,  97],
       [ 85,  